### ISSUE TITLE
requirements.txt is NOT FOUND

### ISSUE THREAD

**Issue by Haoqiu-Yan** [yochaiye/LipVoicer#1]
Thanks for your fantastic work! 

When running `pip install -r requirements.txt` to installing packages required by LipVoicer, I'm having trouble locating the `requirements.txt` file in this repository.  Could you please upload it or direct me to its location?

**Comment by yochaiye** [comment]
Hi, thank you for the positive feedback!

I uploaded the `requirements.txt` file yesterday, and I also updated the code to its latest form.
I hope to complete the `README` file today so it is clear how to use the repo for inference and test

**Comment by Haoqiu-Yan** [comment]
Thanks very much :)
